# This is the title that will be displayed once a player joins.
title: "&aTitle"

# The amount of time that the very first subtitle will fade in for.
first-subtitle-fade-in-time: 1

# The amount of time that the very last subtitle will fade out for.
last-subtitle-fade-out-time: 1

# The subtitles that will be displayed periodically as defined with 'seconds-before-changing'.
subtitle:
  - "&aSubtitle 1"
  - "&aSubtitle 2"
  - "&aSubtitle 3"

# The time in between subtitles displaying.
seconds-before-changing: 7

# Fading config
# How long it takes for the title/subtitle to appear on screen.
fade-in-time: 1

# How long it stays without fading.
stay-time: 1

# How long it takes for the title/subtitle to fade out.
fade-out-time: 1
